# Generated by Django 3.2.7 on 2021-09-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='amazon_warehouses',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='goods_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('bg_price', models.CharField(max_length=200)),
                ('box_height', models.CharField(max_length=200)),
                ('box_length', models.CharField(max_length=200)),
                ('box_width', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('cn_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('hs_code', models.CharField(max_length=200)),
                ('hts', models.CharField(max_length=200)),
                ('is_charged', models.IntegerField(max_length=200)),
                ('is_magnetic', models.IntegerField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('qg_price', models.CharField(max_length=200)),
                ('used', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse', models.CharField(max_length=200)),
                ('overseas_warehouses', models.CharField(max_length=200)),
                ('amazon_warehouses', models.CharField(max_length=200)),
                ('server_model', models.CharField(max_length=200)),
                ('ship_date', models.CharField(max_length=200)),
                ('is_fba', models.IntegerField(max_length=200)),
                ('goods', models.CharField(max_length=200)),
                ('my_order', models.CharField(max_length=200)),
                ('baoguan', models.IntegerField(max_length=200)),
                ('qingguan', models.IntegerField(max_length=200)),
                ('fba_id', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=200)),
                ('box_num', models.IntegerField(max_length=200)),
                ('goods_num', models.IntegerField(max_length=200)),
                ('goods_weight', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='overseas_warehouses',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='server_model',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('shipping_day', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='mytest',
        ),
    ]
