# Generated by Django 3.2.7 on 2021-09-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210910_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server_model',
            name='shipping_day',
        ),
    ]
