# Generated by Django 3.2.7 on 2021-09-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210910_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_list',
            name='imgs',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
