# Generated by Django 3.2.7 on 2021-09-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_goods_list_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='status',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_list',
            name='update_time',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
